name: Update Rates

on:
  repository_dispatch:
    types: [manual_trigger]  # Este es el nombre del evento que enviaremos
  workflow_dispatch:          # Esto te permite ejecutarlo manualmente desde la web

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run update script
        run: python update.py
        timeout-minutes: 2  # Si tarda más de 2 min, GitHub lo mata automáticamente

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add rates.json
          # Verificamos si hay cambios para no fallar si el precio es igual
          if git diff --staged --quiet; then
            echo "No hay cambios en los rates. Saltando commit."
          else
            git commit --amend -m "Rates actualizados: $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || git commit -m "Update rates"
            git push origin main --force
          fi
